###
# curl -i -X POST http://localhost:8080/api/users
#  -H "Content-Type: application/json"
#  -d '{"name":"Sergio Bezerra","email":"teste-jwt@exemplo.com","password":"SenhaForte123!"}'
POST http://localhost:8080/api/users
Content-Type: application/json

{
    "name": "Sergio Bezerra",
    "email": "teste-jwt@exemplo.com",
    "password": "SenhaForte123!"
}

###

# curl -i -X POST http://localhost:8080/api/auth/login
#  -H "Content-Type: application/json"
#  -d '{"email":"teste-jwt@exemplo.com","password":"SenhaForte123!"}'
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
    "email": "teste-jwt@exemplo.com",
    "password": "SenhaForte123!"
}

###


# curl -i -X POST http://localhost:8080/api/auth/login
#  -H "Content-Type: application/json"
#  -d '{"email":"teste-jwt@exemplo.com","password":"SenhaErrada999!"}'
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
    "email": "teste-jwt@exemplo.com",
    "password": "SenhaErrada999!"
}

###


# curl -i -X POST http://localhost:8080/api/auth/login
#  -H "Content-Type: application/json"
#  -d '{"email":"naoexiste@exemplo.com","password":"QualquerCoisa123!"}'
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
    "email": "naoexiste@exemplo.com",
    "password": "QualquerCoisa123!"
}

###


# curl -i http://localhost:8080/api/tasks
GET http://localhost:8080/api/tasks

###

# curl -i -X POST http://localhost:8080/api/auth/login
#  -H "Content-Type: application/json"
#  -d '{"email":"teste-jwt@exemplo.com","password":"SenhaForte123!"}'
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
    "email": "teste-jwt@exemplo.com",
    "password": "SenhaForte123!"
}

###

# curl -i http://localhost:8080/api/tasks
#  -H "Authorization: Bearer <cole o token aqui>"
GET http://localhost:8080/api/tasks
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJmZjU5M2I0Mi1mNGZjLTQ0NjYtYmFiNy1jNzUxM2JiY2Q2NjUiLCJpYXQiOjE3ODU3ODg1ODMsImV4cCI6MTc4NTc5MjE4M30.An4JpHOqXAtUGcmJa1wrMv95Y0hTd23nPZXTQc0O7Fg

###

# curl -i http://localhost:8080/api/tasks
#  -H "Authorization: Bearer token.invalido.aqui"
GET http://localhost:8080/api/tasks
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJmZjU5M2I0Mi1mNGZjTQ0NjYtYmFiNy1jNzUxM2JiY2Q2NjUiLCJpYXQiOjE3ODU3ODc5MTksImV4cCI6MTc4NTc5MTUxOX0.TR408NZae1QlZZEBGpYnGk5kpw7vmaRbVGvSP5dkgbA

###

# curl -i -X POST http://localhost:8080/api/auth/google
#  -H "Content-Type: application/json"
#  -d '{"idToken":"token.invalido.aqui"}'
POST http://localhost:8080/api/auth/google
Content-Type: application/json

{
    "idToken": "eyJhbGciOiJIzI1NiJ9.eyJzdWIiOiJjYzQ0N2UzMi0zOGZkLTQ1ZjEtOTRlMy1jNDk1NjNjYmNiNzMiLCJpYXQiOjE3ODYwMzI1ODYsImV4cCI6MTc4NjAzNjE4Nn0.tHaud-iDhck0DLdZ6rgjd8mh-kKpk_ZZDD88qzA53Do"
}

###

# curl -i http://localhost:8080/api/tasks/dashboard -H "Authorization: Bearer <token>"
GET http://localhost:8080/api/tasks/dashboard
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJjYzQ0N2UzMi0zOGZkLTQ1ZjEtOTRlMy1jNDk1NjNjYmNiNzMiLCJpYXQiOjE3ODYwNTczNDIsImV4cCI6MTc4NjA2MDk0Mn0.c4Ew9fDnGqJVnwdnouHSGlHl_6hR2gRG228dFUgP4L8

###

curl -i http://localhost:8080/api/tasks/b0b03c6e-e7e6-4693-ba18-93bccbd44d19 -H "Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJjYzQ0N2UzMi0zOGZkLTQ1ZjEtOTRlMy1jNDk1NjNjYmNiNzMiLCJpYXQiOjE3ODYwNTczNDIsImV4cCI6MTc4NjA2MDk0Mn0.c4Ew9fDnGqJVnwdnouHSGlHl_6hR2gRG228dFUgP4L8"


########



# curl --request GET
#  --url http://localhost:8080/api/tasks/b0b03c6e-e7e6-4693-ba18-93bccbd44d19
#  --header 'Authorization: Bearer  eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJjYzQ0N2UzMi0zOGZkLTQ1ZjEtOTRlMy1jNDk1NjNjYmNiNzMiLCJpYXQiOjE3ODYwNTczNDIsImV4cCI6MTc4NjA2MDk0Mn0.c4Ew9fDnGqJVnwdnouHSGlHl_6hR2gRG228dFUgP4L8'
GET http://localhost:8080/api/tasks/b0b03c6e-e7e6-4693-ba18-93bccbd44d19
Authorization: Bearer  eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJjYzQ0N2UzMi0zOGZkLTQ1ZjEtOTRlMy1jNDk1NjNjYmNiNzMiLCJpYXQiOjE3ODYwNTczNDIsImV4cCI6MTc4NjA2MDk0Mn0.c4Ew9fDnGqJVnwdnouHSGlHl_6hR2gRG228dFUgP4L8

###



# curl -i http://localhost:8080/api/tasks/b0b03c6e-e7e6-4693-ba18-93bccbd44d19
#  -H "Authorization: Bearer <token-novo>"
GET http://localhost:8080/api/tasks/b0b03c6e-e7e6-4693-ba18-93bccbd44d19
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJjYzQ0N2UzMi0zOGZkLTQ1ZjEtOTRlMy1jNDk1NjNjYmNiNzMiLCJpYXQiOjE3ODYwNTc4NzcsImV4cCI6MTc4NjA2MTQ3N30.QREAzye4aHmufiPnol7Apm5RL_boqnfs-e-fo487GlY

###


